global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'products'
    static_configs:
      - targets: ['host.docker.internal:3008']