version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:root@auth-db:3306/userdb
      - QUEUE_URL=amqp://rabbitmq:5672
    depends_on:
      - auth-db
      - rabbitmq
    volumes:
      - ./auth-service:/usr/src/app # Đồng bộ mã nguồn trong development (nếu cần)
