# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_stream.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'video_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12video_stream.proto\"\"\n\x0cVideoRequest\x12\x12\n\nvideo_path\x18\x01 \x01(\t\"/\n\nVideoChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0b\x66rame_index\x18\x02 \x01(\x05\x32?\n\x12VideoStreamService\x12)\n\tPlayVideo\x12\r.VideoRequest\x1a\x0b.VideoChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOREQUEST']._serialized_start=22
  _globals['_VIDEOREQUEST']._serialized_end=56
  _globals['_VIDEOCHUNK']._serialized_start=58
  _globals['_VIDEOCHUNK']._serialized_end=105
  _globals['_VIDEOSTREAMSERVICE']._serialized_start=107
  _globals['_VIDEOSTREAMSERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
